# Generated by Django 4.1.2 on 2022-10-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('DOCUMENTARIO', 'Documentario'), ('FILME', 'Filme'), ('SERIE', 'Anime'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
